name: 'Setup .NET'
description: 'Sets up .NET environment'
runs:
  using: "composite"
  steps:
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: '10.0.x' 